In [2]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
arr = np.array(42)

print(arr)

42


In [7]:
type(arr)

numpy.ndarray

In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


File Handling

In [26]:
file = open('txt.txt' , 'r')

In [22]:
for line in file:
    print(line)

hello world

world

aditya

pk


In [25]:
print(file.read())

hello world
world
aditya
pk


In [27]:
print(file.read(5))

hello


In [30]:
file = open('txt.txt','w')
file.write("This is the write command ")
file.write("It allows us to write in a particular file")
file.close()

In [33]:
with open("txt.txt") as file:
    data = file.read()
    print(data)

This is the write command It allows us to write in a particular file


In [34]:
with open("txt.txt" , "w") as f:
    f.write("Hello World!")

In [41]:
with open("txt.txt") as f:
    data = f.readlines()
    for line in data:
        word = line.split()
        print(word)

['Hello', 'World!']
['Hello']
['hey']


In [42]:
import os
os.remove("txt.txt")

In [57]:
f = open('file.txt' , 'a')
f.write("More content!")
f.close()

In [ ]:
f = open('newfile.txt' , 'x')

In [59]:
f = open("file.txt", "r")
print(f.readline(),end="")
print(f.readline() , end = "")

hello
hey


In [49]:
f = open("file.txt", "r")
for x in f:
  print(x)

hello

hey

More content!


In [51]:
f.close()

In [52]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [66]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [67]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [68]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [69]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [73]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [75]:
age = input("enter your age")
f = open("age.txt" , 'w')
f.write(age)
print("age is printed on the text file")
f.close()
age1 = input("enter your age")
f = open("age.txt" , 'w')
w = f.write(age1)
f.close()

age is printed on the text file


In [76]:
f = open("age.txt" , 'r')
print(f.name)
print(f.mode)
print(f.closed)
print(f.encoding)
f.close()
print(f.closed)

age.txt
r
False
cp1252
True


In [81]:
f = open("newfile.txt" , 'w')
f.write("hello world \n")
f.write("bye world \n" )
f.write("hello world \n")
f.write("bye everyone \n")
f.close()
read = open("newfile.txt" , 'r')
print(read.read())

hello world 
bye world 
hello world 
bye everyone 

